import { ConstantsTypes } from "../../types";

export const constants: Readonly<ConstantsTypes> = {
    bearer: "Bearer ",
    create_new_team: "Create new team",
    valid: "valid",
    yes: "yes",
    no: "no",
    mainColor: "560BAD",
    emailPattern: /^[\w\.-]{3,}@[\w\.-]+\.[a-zA-Z]{2,}$/,
    allProfilesType: "all",
    favoriteProfilesType: "favorite",
    customFolderProfilesType: "custom folder",
    execute: "execute",
    close: "close",
    cryptomus: "Cryptomus",
    convert: "Convert",
    merge: "Merge",
    paths: {
        home: "/", // this is the login section when not authorized, and if authorized, then the account section
        sign_up: "/sign_up",
        dashboardHome: "/home",
        profiles: "/profiles",
        proxy: "/proxy",
        account: "/account",
        cookies: "/cookies",
        store: "/store",
        notifications: "/notifications",
        settings: "/settings",
        settings_security: "security",
        settings_personalization: "personalization",
        settings_team: "team",
        settings_notifications: "notifications",
        change_email: "account/change-email",
        change_password: "change-password",
        change_sidebar_menu: "change-sidebar",
        via_email: "via-email",
        via_masq_panel: "via-masq-panel",
        create_folder: "create-folder",
        subscription: "subscription",
        devices: "devices",
        teams: "teams",
        manage: "manage",
        createNewProfile: "/new_profile",
        buySubscriptionPlan: "buy-subscription",
        topUpWallet: "top-up-wallet",
        editProfile: "edit-profile",
        getResolutions: "/v2/profile/hardware/screen",
        getCores: "/v2/profile/hardware/cores",
        getVideoCards: "/v2/profile/hardware/videoCard",
        getRams: "/v2/profile/hardware/ram",
        getCountries: "/v2/profile/countries/",
    },
    endpoints: {
        userLogin: "/v2/user/login",
        registration: "/v2/user/registration",
        confirmEmail: "/v2/user/confirmEmail/",
        userAuth: "/v2/user/auth/",
        getTariffList: "/user/getTariffList/",
        removeSession: "/v2/user/removeSession/",
        logOut: "/v2/user/logout/",
        getAllNotifications: "/v2/message/",
        readAllNotifications: "/v2/message/readAll",
        readNotification: "/v2/message/read",
        checkNameFree: "/v2/user/checkNameFree/",
        sendConfirmCode: "/v2/user/sendConfirmCode",
        sendRecoveryCode: "/v2/user/sendRecoveryCode",
        checkRecoveryCode: "/v2/user/checkRecoveryCode",
        recoveryPassword: "/v2/user/recoveryPassword",
        changeName: "/v2/user/changeName/",
        removeAllSession: "/v2/user/removeAllSession/",
        changePassword: "/v2/user/changePassword/",
        getFolders: "/v2/profile/getFolders",
        createFolder: "/v2/profile/createFolder",
        getProfiles: "/v2/profile/getProfiles/",
        getProfile: "/v2/profile/getProfile/",
        sendInviteCode: "/v2/team/sendInviteCode/",
        changeTeamName: "/v2/team/changeName",
        changeEmailSendConfirmCode: "/v2/user/changeEmail/sendConfirmCode",
        confirmCurrentEmail: "/v2/user/changeEmail/confirmCurrentEmail/",
        setNewEmail: "/v2/user/changeEmail/setNewEmail/",
        confirmNewEmail: "/v2/user/changeEmail/confirmNewEmail/",
        setInvitesAccess: "/v2/team/setInvitesAccess/",
        appSettings: "/v2/appSettings",
        deleteAccount: "/v2/user/deleteAccount/",
        notificationsSettings: "/v2/notificationSettings/",
        removeOtherSessions: "/v2/user/removeOtherSessions/",
        setupTfa: "/v2/user/tfa/setup",
        verifyTfa: "/v2/user/tfa/verify",
        removeTfa: "/v2/user/tfa/remove",
        payments: "/v2/cryptomus/paymentBalance/",
        paymentsTariff: "/v2/cryptomus/paymentSub/",
        promoCode: "/v2/promoCodes/check/",
        getBrowsers: "/v2/profile/browsers",
        getBrowserVersions: "/v2/profile/browserVersions",
        tariffList: "/v2/sub/tariffList/",
        buySubscriptionPlan: "/v2/sub/buy/",
        changeFolderIcon: "/v2/profile/changeFolderIcon",
        changeFolderName: "/v2/profile/changeFolderName",
        getLanguages: "/v2/profile/languages/",
        getUserAgent: "/v2/profile/userAgent/",
        createProfile: "/v2/profile/create",
        deleteFolder: "/v2/profile/deleteFolder",
        changeTariff: "/v2/sub/changeTariff/",
        getGeocode: "/v2/profile/geocode/",
        checkProxy: "/v2/proxy/check/",
        getSessions: "/v2/user/getSessions/",
        getMemberSession: "/v2/team/getMembersSessions/",
        shareFolder: "/v2/profile/shareFolder/",
        shareProfile: "/v2/profile/shareProfile/",
        deleteProfile: "/v2/profile/deleteProfile/",
        duplicateProfile: "/v2/profile/duplicate",
        moveProfileToFolder: "/v2/profile/moveProfileToFolder/",
        leaveFromTeam: "/v2/team/leave/",
        getTeamsInfo: "/v2/team/getInfo",
        useInviteCode: "/v2/team/useInviteCode/",
        changeRole: "/v2/team/changeRole",
        acceptShare: "/v2/profile/acceptShare/",
        updateProfile: "/v2/profile/update",
        removeUserForTeam: "/v2/team/removeUser/",
        addProfilesToFolder: "/v2/profile/addProfilesToFolder/",
        getAppVersion: "/v2/appVersion",
    },
    eventsMsg: {
        types: {
            recoveryPasswordSuccess: "Password successfully recovered",
            passwordChangeSuccess: "Password successfully changed",
            emailChangeSuccess: "Email successfully changed",
        },
        headers: {
            success: "success",
        },
        messages: {
            haveNewPassword: "have_a_new_password",
            haveNewEmail: "have_a_new_email",
            accountSuccessfullyCreated: "account_successfully_created",
        },
    },
    helperModalTypes: {
        endAllSessions: "End All Sessions",
        deleteAccount: "Delete Account",
        chooseSubPlanMethod: "Merge or Convert Subscription Plan",
        leaveTeam: "Leave Team",
        deleteTeamItem: "Delete Team Item",
        deleteFolder: "Delete Folder",
        shareFolder: "Share Folder",
        shareProfile: "Share Profile",
        foundLocalProfiles: "Found Local Profiles",
        exportFolder: "Export Folder",
        importProfiles: "Import Profiles",
    },
    profilesIconsNames: [
        "icon_triangle",
        "icon_trapezoid",
        "icon_rhombus",
        "icon_parallelogram",
        "icon_pentagon",
        "icon_hexagon",
        "icon_frame",
        "icon_rabbet",
        "icon_circle",
        "icon_ellipse",
        "icon_custom_octagonal",
        "icon_custom_square",
        "icon_custom_loading",
        "icon_custom_bevel",
        "icon_custom_up",
        "icon_close",
    ],
    notifyTypes: {
        success: "#0F9918",
        invite: "#560BAD",
        error: "#E50000",
    },
    notificationTypes: {
        invite: "invite",
        share_profile: "share_profile",
        share_profile_folder: "share_profile_folder",
        message: "message",
    },
    userRoleTypes: {
        leader: "leader",
        moder: "moder",
        member: "member",
    },
    appVersionStatusTypes: {
        checking: "checking",
        invalid: "invalid",
        valid: "valid",
    },
    chooseParameterTypes: {
        folder: "Folder",
        name: "Name",
        comment: "Comment",
        os: "OS",
        platform: "Platform",
        browser: "Browser",
        browser_version: "Browser Version",
        screen_resolution: "Screen Resolution",
        cpu: "CPU",
        gpu: "GPU",
        ram: "RAM",
        country: "Country",
        language: "Language",
        timezone: "Timezone",
    },
};
