import { OffsetsTypes } from "../../types";

export const offsets: OffsetsTypes[] = [
    {
        location: "Pacific/Niue",
        city: "Niue",
        region: "Pacific",
        standard: "Niue Standard Time",
        daylight: "Niue Summer Time",
        human: "Niue / Pacific (GMT -11:00)",
        offset: -660,
    },
    {
        location: "Pacific/Pago Pago",
        city: "Pago Pago",
        region: "Pacific",
        standard: "Pago Pago Standard Time",
        daylight: "Pago Pago Summer Time",
        human: "Pago Pago / Pacific (GMT -11:00)",
        offset: -660,
    },
    {
        location: "Pacific/Honolulu",
        city: "Honolulu",
        region: "Pacific",
        standard: "Honolulu Standard Time",
        daylight: "Honolulu Summer Time",
        human: "Honolulu / Pacific (GMT -10:00)",
        offset: -600,
    },
    {
        location: "Pacific/Rarotonga",
        city: "Rarotonga",
        region: "Pacific",
        standard: "Rarotonga Standard Time",
        daylight: "Rarotonga Summer Time",
        human: "Rarotonga / Pacific (GMT -10:00)",
        offset: -600,
    },
    {
        location: "Pacific/Tahiti",
        city: "Tahiti",
        region: "Pacific",
        standard: "Tahiti Standard Time",
        daylight: "Tahiti Summer Time",
        human: "Tahiti / Pacific (GMT -10:00)",
        offset: -600,
    },
    {
        location: "America/Anchorage",
        city: "Anchorage",
        region: "America",
        standard: "Anchorage Standard Time",
        daylight: "Anchorage Summer Time",
        human: "Anchorage / America (GMT -9:00)",
        offset: -540,
    },
    {
        location: "Pacific/Gambier",
        city: "Gambier",
        region: "Pacific",
        standard: "Gambier Standard Time",
        daylight: "Gambier Summer Time",
        human: "Gambier / Pacific (GMT -9:00)",
        offset: -540,
    },
    {
        location: "Pacific/Marquesas",
        city: "Marquesas",
        region: "Pacific",
        standard: "Marquesas Standard Time",
        daylight: "Marquesas Summer Time",
        human: "Marquesas / Pacific (GMT -9:30)",
        offset: -510,
    },
    {
        location: "America/Los Angeles",
        city: "Los Angeles",
        region: "America",
        standard: "Los Angeles Standard Time",
        daylight: "Los Angeles Summer Time",
        human: "Los Angeles / America (GMT -8:00)",
        offset: -480,
    },
    {
        location: "Pacific/Pitcairn",
        city: "Pitcairn",
        region: "Pacific",
        standard: "Pitcairn Standard Time",
        daylight: "Pitcairn Summer Time",
        human: "Pitcairn / Pacific (GMT -8:00)",
        offset: -480,
    },
    {
        location: "America/Tijuana",
        city: "Tijuana",
        region: "America",
        standard: "Tijuana Standard Time",
        daylight: "Tijuana Summer Time",
        human: "Tijuana / America (GMT -8:00)",
        offset: -480,
    },
    {
        location: "America/Vancouver",
        city: "Vancouver",
        region: "America",
        standard: "Vancouver Standard Time",
        daylight: "Vancouver Summer Time",
        human: "Vancouver / America (GMT -8:00)",
        offset: -480,
    },
    {
        location: "America/Whitehorse",
        city: "Whitehorse",
        region: "America",
        standard: "Whitehorse Standard Time",
        daylight: "Whitehorse Summer Time",
        human: "Whitehorse / America (GMT -8:00)",
        offset: -480,
    },
    {
        location: "America/Dawson Creek",
        city: "Dawson Creek",
        region: "America",
        standard: "Dawson Creek Standard Time",
        daylight: "Dawson Creek Summer Time",
        human: "Dawson Creek / America (GMT -7:00)",
        offset: -420,
    },
    {
        location: "America/Denver",
        city: "Denver",
        region: "America",
        standard: "Denver Standard Time",
        daylight: "Denver Summer Time",
        human: "Denver / America (GMT -7:00)",
        offset: -420,
    },
    {
        location: "America/Edmonton",
        city: "Edmonton",
        region: "America",
        standard: "Edmonton Standard Time",
        daylight: "Edmonton Summer Time",
        human: "Edmonton / America (GMT -7:00)",
        offset: -420,
    },
    {
        location: "America/Hermosillo",
        city: "Hermosillo",
        region: "America",
        standard: "Hermosillo Standard Time",
        daylight: "Hermosillo Summer Time",
        human: "Hermosillo / America (GMT -7:00)",
        offset: -420,
    },
    {
        location: "America/Mazatlan",
        city: "Mazatlan",
        region: "America",
        standard: "Mazatlan Standard Time",
        daylight: "Mazatlan Summer Time",
        human: "Mazatlan / America (GMT -7:00)",
        offset: -420,
    },
    {
        location: "America/Phoenix",
        city: "Phoenix",
        region: "America",
        standard: "Phoenix Standard Time",
        daylight: "Phoenix Summer Time",
        human: "Phoenix / America (GMT -7:00)",
        offset: -420,
    },
    {
        location: "America/Yellowknife",
        city: "Yellowknife",
        region: "America",
        standard: "Yellowknife Standard Time",
        daylight: "Yellowknife Summer Time",
        human: "Yellowknife / America (GMT -7:00)",
        offset: -420,
    },
    {
        location: "America/Belize",
        city: "Belize",
        region: "America",
        standard: "Belize Standard Time",
        daylight: "Belize Summer Time",
        human: "Belize / America (GMT -6:00)",
        offset: -360,
    },
    {
        location: "America/Chicago",
        city: "Chicago",
        region: "America",
        standard: "Chicago Standard Time",
        daylight: "Chicago Summer Time",
        human: "Chicago / America (GMT -6:00)",
        offset: -360,
    },
    {
        location: "America/Costa Rica",
        city: "Costa Rica",
        region: "America",
        standard: "Costa Rica Standard Time",
        daylight: "Costa Rica Summer Time",
        human: "Costa Rica / America (GMT -6:00)",
        offset: -360,
    },
    {
        location: "America/El Salvador",
        city: "El Salvador",
        region: "America",
        standard: "El Salvador Standard Time",
        daylight: "El Salvador Summer Time",
        human: "El Salvador / America (GMT -6:00)",
        offset: -360,
    },
    {
        location: "Pacific/Galapagos",
        city: "Galapagos",
        region: "Pacific",
        standard: "Galapagos Standard Time",
        daylight: "Galapagos Summer Time",
        human: "Galapagos / Pacific (GMT -6:00)",
        offset: -360,
    },
    {
        location: "America/Guatemala",
        city: "Guatemala",
        region: "America",
        standard: "Guatemala Standard Time",
        daylight: "Guatemala Summer Time",
        human: "Guatemala / America (GMT -6:00)",
        offset: -360,
    },
    {
        location: "America/Managua",
        city: "Managua",
        region: "America",
        standard: "Managua Standard Time",
        daylight: "Managua Summer Time",
        human: "Managua / America (GMT -6:00)",
        offset: -360,
    },
    {
        location: "America/Mexico City",
        city: "Mexico City",
        region: "America",
        standard: "Mexico City Standard Time",
        daylight: "Mexico City Summer Time",
        human: "Mexico City / America (GMT -6:00)",
        offset: -360,
    },
    {
        location: "America/Regina",
        city: "Regina",
        region: "America",
        standard: "Regina Standard Time",
        daylight: "Regina Summer Time",
        human: "Regina / America (GMT -6:00)",
        offset: -360,
    },
    {
        location: "America/Tegucigalpa",
        city: "Tegucigalpa",
        region: "America",
        standard: "Tegucigalpa Standard Time",
        daylight: "Tegucigalpa Summer Time",
        human: "Tegucigalpa / America (GMT -6:00)",
        offset: -360,
    },
    {
        location: "America/Winnipeg",
        city: "Winnipeg",
        region: "America",
        standard: "Winnipeg Standard Time",
        daylight: "Winnipeg Summer Time",
        human: "Winnipeg / America (GMT -6:00)",
        offset: -360,
    },
    {
        location: "America/Bogota",
        city: "Bogota",
        region: "America",
        standard: "Bogota Standard Time",
        daylight: "Bogota Summer Time",
        human: "Bogota / America (GMT -5:00)",
        offset: -300,
    },
    {
        location: "America/Cancun",
        city: "Cancun",
        region: "America",
        standard: "Cancun Standard Time",
        daylight: "Cancun Summer Time",
        human: "Cancun / America (GMT -5:00)",
        offset: -300,
    },
    {
        location: "America/Cayman",
        city: "Cayman",
        region: "America",
        standard: "Cayman Standard Time",
        daylight: "Cayman Summer Time",
        human: "Cayman / America (GMT -5:00)",
        offset: -300,
    },
    {
        location: "Pacific/Easter",
        city: "Easter",
        region: "Pacific",
        standard: "Easter Standard Time",
        daylight: "Easter Summer Time",
        human: "Easter / Pacific (GMT -5:00)",
        offset: -300,
    },
    {
        location: "America/Guayaquil",
        city: "Guayaquil",
        region: "America",
        standard: "Guayaquil Standard Time",
        daylight: "Guayaquil Summer Time",
        human: "Guayaquil / America (GMT -5:00)",
        offset: -300,
    },
    {
        location: "America/Havana",
        city: "Havana",
        region: "America",
        standard: "Havana Standard Time",
        daylight: "Havana Summer Time",
        human: "Havana / America (GMT -5:00)",
        offset: -300,
    },
    {
        location: "America/Iqaluit",
        city: "Iqaluit",
        region: "America",
        standard: "Iqaluit Standard Time",
        daylight: "Iqaluit Summer Time",
        human: "Iqaluit / America (GMT -5:00)",
        offset: -300,
    },
    {
        location: "America/Jamaica",
        city: "Jamaica",
        region: "America",
        standard: "Jamaica Standard Time",
        daylight: "Jamaica Summer Time",
        human: "Jamaica / America (GMT -5:00)",
        offset: -300,
    },
    {
        location: "America/Lima",
        city: "Lima",
        region: "America",
        standard: "Lima Standard Time",
        daylight: "Lima Summer Time",
        human: "Lima / America (GMT -5:00)",
        offset: -300,
    },
    {
        location: "America/Nassau",
        city: "Nassau",
        region: "America",
        standard: "Nassau Standard Time",
        daylight: "Nassau Summer Time",
        human: "Nassau / America (GMT -5:00)",
        offset: -300,
    },
    {
        location: "America/New York",
        city: "New York",
        region: "America",
        standard: "New York Standard Time",
        daylight: "New York Summer Time",
        human: "New York / America (GMT -5:00)",
        offset: -300,
    },
    {
        location: "America/Panama",
        city: "Panama",
        region: "America",
        standard: "Panama Standard Time",
        daylight: "Panama Summer Time",
        human: "Panama / America (GMT -5:00)",
        offset: -300,
    },
    {
        location: "America/Port-au-Prince",
        city: "Port-au-Prince",
        region: "America",
        standard: "Port-au-Prince Standard Time",
        daylight: "Port-au-Prince Summer Time",
        human: "Port-au-Prince / America (GMT -5:00)",
        offset: -300,
    },
    {
        location: "America/Rio Branco",
        city: "Rio Branco",
        region: "America",
        standard: "Rio Branco Standard Time",
        daylight: "Rio Branco Summer Time",
        human: "Rio Branco / America (GMT -5:00)",
        offset: -300,
    },
    {
        location: "America/Toronto",
        city: "Toronto",
        region: "America",
        standard: "Toronto Standard Time",
        daylight: "Toronto Summer Time",
        human: "Toronto / America (GMT -5:00)",
        offset: -300,
    },
    {
        location: "America/Barbados",
        city: "Barbados",
        region: "America",
        standard: "Barbados Standard Time",
        daylight: "Barbados Summer Time",
        human: "Barbados / America (GMT -4:00)",
        offset: -240,
    },
    {
        location: "Atlantic/Bermuda",
        city: "Bermuda",
        region: "Atlantic",
        standard: "Bermuda Standard Time",
        daylight: "Bermuda Summer Time",
        human: "Bermuda / Atlantic (GMT -4:00)",
        offset: -240,
    },
    {
        location: "America/Boa Vista",
        city: "Boa Vista",
        region: "America",
        standard: "Boa Vista Standard Time",
        daylight: "Boa Vista Summer Time",
        human: "Boa Vista / America (GMT -4:00)",
        offset: -240,
    },
    {
        location: "America/Curacao",
        city: "Curacao",
        region: "America",
        standard: "Curacao Standard Time",
        daylight: "Curacao Summer Time",
        human: "Curacao / America (GMT -4:00)",
        offset: -240,
    },
    {
        location: "America/Grand Turk",
        city: "Grand Turk",
        region: "America",
        standard: "Grand Turk Standard Time",
        daylight: "Grand Turk Summer Time",
        human: "Grand Turk / America (GMT -4:00)",
        offset: -240,
    },
    {
        location: "America/Guyana",
        city: "Guyana",
        region: "America",
        standard: "Guyana Standard Time",
        daylight: "Guyana Summer Time",
        human: "Guyana / America (GMT -4:00)",
        offset: -240,
    },
    {
        location: "America/Halifax",
        city: "Halifax",
        region: "America",
        standard: "Halifax Standard Time",
        daylight: "Halifax Summer Time",
        human: "Halifax / America (GMT -4:00)",
        offset: -240,
    },
    {
        location: "America/La Paz",
        city: "La Paz",
        region: "America",
        standard: "La Paz Standard Time",
        daylight: "La Paz Summer Time",
        human: "La Paz / America (GMT -4:00)",
        offset: -240,
    },
    {
        location: "America/Manaus",
        city: "Manaus",
        region: "America",
        standard: "Manaus Standard Time",
        daylight: "Manaus Summer Time",
        human: "Manaus / America (GMT -4:00)",
        offset: -240,
    },
    {
        location: "America/Martinique",
        city: "Martinique",
        region: "America",
        standard: "Martinique Standard Time",
        daylight: "Martinique Summer Time",
        human: "Martinique / America (GMT -4:00)",
        offset: -240,
    },
    {
        location: "America/Port of Spain",
        city: "Port of Spain",
        region: "America",
        standard: "Port of Spain Standard Time",
        daylight: "Port of Spain Summer Time",
        human: "Port of Spain / America (GMT -4:00)",
        offset: -240,
    },
    {
        location: "America/Porto Velho",
        city: "Porto Velho",
        region: "America",
        standard: "Porto Velho Standard Time",
        daylight: "Porto Velho Summer Time",
        human: "Porto Velho / America (GMT -4:00)",
        offset: -240,
    },
    {
        location: "America/Puerto Rico",
        city: "Puerto Rico",
        region: "America",
        standard: "Puerto Rico Standard Time",
        daylight: "Puerto Rico Summer Time",
        human: "Puerto Rico / America (GMT -4:00)",
        offset: -240,
    },
    {
        location: "America/Santo Domingo",
        city: "Santo Domingo",
        region: "America",
        standard: "Santo Domingo Standard Time",
        daylight: "Santo Domingo Summer Time",
        human: "Santo Domingo / America (GMT -4:00)",
        offset: -240,
    },
    {
        location: "America/Thule",
        city: "Thule",
        region: "America",
        standard: "Thule Standard Time",
        daylight: "Thule Summer Time",
        human: "Thule / America (GMT -4:00)",
        offset: -240,
    },
    {
        location: "America/Caracas",
        city: "Caracas",
        region: "America",
        standard: "Caracas Standard Time",
        daylight: "Caracas Summer Time",
        human: "Caracas / America (GMT -4:30)",
        offset: -210,
    },
    {
        location: "America/Araguaina",
        city: "Araguaina",
        region: "America",
        standard: "Araguaina Standard Time",
        daylight: "Araguaina Summer Time",
        human: "Araguaina / America (GMT -3:00)",
        offset: -180,
    },
    {
        location: "America/Argentina/Buenos Aires",
        city: "Argentina",
        region: "America",
        standard: "Argentina Standard Time",
        daylight: "Argentina Summer Time",
        human: "Argentina / America (GMT -3:00)",
        offset: -180,
    },
    {
        location: "America/Asuncion",
        city: "Asuncion",
        region: "America",
        standard: "Asuncion Standard Time",
        daylight: "Asuncion Summer Time",
        human: "Asuncion / America (GMT -3:00)",
        offset: -180,
    },
    {
        location: "America/Bahia",
        city: "Bahia",
        region: "America",
        standard: "Bahia Standard Time",
        daylight: "Bahia Summer Time",
        human: "Bahia / America (GMT -3:00)",
        offset: -180,
    },
    {
        location: "America/Belem",
        city: "Belem",
        region: "America",
        standard: "Belem Standard Time",
        daylight: "Belem Summer Time",
        human: "Belem / America (GMT -3:00)",
        offset: -180,
    },
    {
        location: "America/Campo Grande",
        city: "Campo Grande",
        region: "America",
        standard: "Campo Grande Standard Time",
        daylight: "Campo Grande Summer Time",
        human: "Campo Grande / America (GMT -3:00)",
        offset: -180,
    },
    {
        location: "America/Cayenne",
        city: "Cayenne",
        region: "America",
        standard: "Cayenne Standard Time",
        daylight: "Cayenne Summer Time",
        human: "Cayenne / America (GMT -3:00)",
        offset: -180,
    },
    {
        location: "America/Cuiaba",
        city: "Cuiaba",
        region: "America",
        standard: "Cuiaba Standard Time",
        daylight: "Cuiaba Summer Time",
        human: "Cuiaba / America (GMT -3:00)",
        offset: -180,
    },
    {
        location: "America/Fortaleza",
        city: "Fortaleza",
        region: "America",
        standard: "Fortaleza Standard Time",
        daylight: "Fortaleza Summer Time",
        human: "Fortaleza / America (GMT -3:00)",
        offset: -180,
    },
    {
        location: "America/Godthab",
        city: "Godthab",
        region: "America",
        standard: "Godthab Standard Time",
        daylight: "Godthab Summer Time",
        human: "Godthab / America (GMT -3:00)",
        offset: -180,
    },
    {
        location: "America/Maceio",
        city: "Maceio",
        region: "America",
        standard: "Maceio Standard Time",
        daylight: "Maceio Summer Time",
        human: "Maceio / America (GMT -3:00)",
        offset: -180,
    },
    {
        location: "America/Miquelon",
        city: "Miquelon",
        region: "America",
        standard: "Miquelon Standard Time",
        daylight: "Miquelon Summer Time",
        human: "Miquelon / America (GMT -3:00)",
        offset: -180,
    },
    {
        location: "America/Montevideo",
        city: "Montevideo",
        region: "America",
        standard: "Montevideo Standard Time",
        daylight: "Montevideo Summer Time",
        human: "Montevideo / America (GMT -3:00)",
        offset: -180,
    },
    {
        location: "Antarctica/Palmer",
        city: "Palmer",
        region: "Antarctica",
        standard: "Palmer Standard Time",
        daylight: "Palmer Summer Time",
        human: "Palmer / Antarctica (GMT -3:00)",
        offset: -180,
    },
    {
        location: "America/Paramaribo",
        city: "Paramaribo",
        region: "America",
        standard: "Paramaribo Standard Time",
        daylight: "Paramaribo Summer Time",
        human: "Paramaribo / America (GMT -3:00)",
        offset: -180,
    },
    {
        location: "America/Recife",
        city: "Recife",
        region: "America",
        standard: "Recife Standard Time",
        daylight: "Recife Summer Time",
        human: "Recife / America (GMT -3:00)",
        offset: -180,
    },
    {
        location: "Antarctica/Rothera",
        city: "Rothera",
        region: "Antarctica",
        standard: "Rothera Standard Time",
        daylight: "Rothera Summer Time",
        human: "Rothera / Antarctica (GMT -3:00)",
        offset: -180,
    },
    {
        location: "America/Santiago",
        city: "Santiago",
        region: "America",
        standard: "Santiago Standard Time",
        daylight: "Santiago Summer Time",
        human: "Santiago / America (GMT -3:00)",
        offset: -180,
    },
    {
        location: "Atlantic/Stanley",
        city: "Stanley",
        region: "Atlantic",
        standard: "Stanley Standard Time",
        daylight: "Stanley Summer Time",
        human: "Stanley / Atlantic (GMT -3:00)",
        offset: -180,
    },
    {
        location: "America/St Johns",
        city: "St Johns",
        region: "America",
        standard: "St Johns Standard Time",
        daylight: "St Johns Summer Time",
        human: "St Johns / America (GMT -3:30)",
        offset: -150,
    },
    {
        location: "America/Noronha",
        city: "Noronha",
        region: "America",
        standard: "Noronha Standard Time",
        daylight: "Noronha Summer Time",
        human: "Noronha / America (GMT -2:00)",
        offset: -120,
    },
    {
        location: "America/Sao Paulo",
        city: "Sao Paulo",
        region: "America",
        standard: "Sao Paulo Standard Time",
        daylight: "Sao Paulo Summer Time",
        human: "Sao Paulo / America (GMT -2:00)",
        offset: -120,
    },
    {
        location: "Atlantic/South Georgia",
        city: "South Georgia",
        region: "Atlantic",
        standard: "South Georgia Standard Time",
        daylight: "South Georgia Summer Time",
        human: "South Georgia / Atlantic (GMT -2:00)",
        offset: -120,
    },
    {
        location: "Atlantic/Azores",
        city: "Azores",
        region: "Atlantic",
        standard: "Azores Standard Time",
        daylight: "Azores Summer Time",
        human: "Azores / Atlantic (GMT -1:00)",
        offset: -60,
    },
    {
        location: "Atlantic/Cape Verde",
        city: "Cape Verde",
        region: "Atlantic",
        standard: "Cape Verde Standard Time",
        daylight: "Cape Verde Summer Time",
        human: "Cape Verde / Atlantic (GMT -1:00)",
        offset: -60,
    },
    {
        location: "America/Scoresbysund",
        city: "Scoresbysund",
        region: "America",
        standard: "Scoresbysund Standard Time",
        daylight: "Scoresbysund Summer Time",
        human: "Scoresbysund / America (GMT -1:00)",
        offset: -60,
    },
    {
        location: "Africa/Abidjan",
        city: "Abidjan",
        region: "Africa",
        standard: "Abidjan Standard Time",
        daylight: "Abidjan Summer Time",
        human: "Abidjan / Africa (GMT 0:00)",
        offset: 0,
    },
    {
        location: "Africa/Accra",
        city: "Accra",
        region: "Africa",
        standard: "Accra Standard Time",
        daylight: "Accra Summer Time",
        human: "Accra / Africa (GMT 0:00)",
        offset: 0,
    },
    {
        location: "Africa/Bissau",
        city: "Bissau",
        region: "Africa",
        standard: "Bissau Standard Time",
        daylight: "Bissau Summer Time",
        human: "Bissau / Africa (GMT 0:00)",
        offset: 0,
    },
    {
        location: "Atlantic/Canary",
        city: "Canary",
        region: "Atlantic",
        standard: "Canary Standard Time",
        daylight: "Canary Summer Time",
        human: "Canary / Atlantic (GMT 0:00)",
        offset: 0,
    },
    {
        location: "Africa/Casablanca",
        city: "Casablanca",
        region: "Africa",
        standard: "Casablanca Standard Time",
        daylight: "Casablanca Summer Time",
        human: "Casablanca / Africa (GMT 0:00)",
        offset: 0,
    },
    {
        location: "America/Danmarkshavn",
        city: "Danmarkshavn",
        region: "America",
        standard: "Danmarkshavn Standard Time",
        daylight: "Danmarkshavn Summer Time",
        human: "Danmarkshavn / America (GMT 0:00)",
        offset: 0,
    },
    {
        location: "Europe/Dublin",
        city: "Dublin",
        region: "Europe",
        standard: "Dublin Standard Time",
        daylight: "Dublin Summer Time",
        human: "Dublin / Europe (GMT 0:00)",
        offset: 0,
    },
    {
        location: "Africa/El Aaiun",
        city: "El Aaiun",
        region: "Africa",
        standard: "El Aaiun Standard Time",
        daylight: "El Aaiun Summer Time",
        human: "El Aaiun / Africa (GMT 0:00)",
        offset: 0,
    },
    {
        location: "Atlantic/Faroe",
        city: "Faroe",
        region: "Atlantic",
        standard: "Faroe Standard Time",
        daylight: "Faroe Summer Time",
        human: "Faroe / Atlantic (GMT 0:00)",
        offset: 0,
    },
    {
        location: "Etc/GMT",
        city: "GMT",
        region: "Etc",
        standard: "GMT Standard Time",
        daylight: "GMT Summer Time",
        human: "GMT / Etc (GMT 0:00)",
        offset: 0,
    },
    {
        location: "Europe/Lisbon",
        city: "Lisbon",
        region: "Europe",
        standard: "Lisbon Standard Time",
        daylight: "Lisbon Summer Time",
        human: "Lisbon / Europe (GMT 0:00)",
        offset: 0,
    },
    {
        location: "Europe/London",
        city: "London",
        region: "Europe",
        standard: "London Standard Time",
        daylight: "London Summer Time",
        human: "London / Europe (GMT 0:00)",
        offset: 0,
    },
    {
        location: "Africa/Monrovia",
        city: "Monrovia",
        region: "Africa",
        standard: "Monrovia Standard Time",
        daylight: "Monrovia Summer Time",
        human: "Monrovia / Africa (GMT 0:00)",
        offset: 0,
    },
    {
        location: "Atlantic/Reykjavik",
        city: "Reykjavik",
        region: "Atlantic",
        standard: "Reykjavik Standard Time",
        daylight: "Reykjavik Summer Time",
        human: "Reykjavik / Atlantic (GMT 0:00)",
        offset: 0,
    },
    {
        location: "Africa/Algiers",
        city: "Algiers",
        region: "Africa",
        standard: "Algiers Standard Time",
        daylight: "Algiers Summer Time",
        human: "Algiers / Africa (GMT +01:00)",
        offset: 60,
    },
    {
        location: "Europe/Amsterdam",
        city: "Amsterdam",
        region: "Europe",
        standard: "Amsterdam Standard Time",
        daylight: "Amsterdam Summer Time",
        human: "Amsterdam / Europe (GMT +01:00)",
        offset: 60,
    },
    {
        location: "Europe/Andorra",
        city: "Andorra",
        region: "Europe",
        standard: "Andorra Standard Time",
        daylight: "Andorra Summer Time",
        human: "Andorra / Europe (GMT +01:00)",
        offset: 60,
    },
    {
        location: "Europe/Belgrade",
        city: "Belgrade",
        region: "Europe",
        standard: "Belgrade Standard Time",
        daylight: "Belgrade Summer Time",
        human: "Belgrade / Europe (GMT +01:00)",
        offset: 60,
    },
    {
        location: "Europe/Berlin",
        city: "Berlin",
        region: "Europe",
        standard: "Berlin Standard Time",
        daylight: "Berlin Summer Time",
        human: "Berlin / Europe (GMT +01:00)",
        offset: 60,
    },
    {
        location: "Europe/Brussels",
        city: "Brussels",
        region: "Europe",
        standard: "Brussels Standard Time",
        daylight: "Brussels Summer Time",
        human: "Brussels / Europe (GMT +01:00)",
        offset: 60,
    },
    {
        location: "Europe/Budapest",
        city: "Budapest",
        region: "Europe",
        standard: "Budapest Standard Time",
        daylight: "Budapest Summer Time",
        human: "Budapest / Europe (GMT +01:00)",
        offset: 60,
    },
    {
        location: "Africa/Ceuta",
        city: "Ceuta",
        region: "Africa",
        standard: "Ceuta Standard Time",
        daylight: "Ceuta Summer Time",
        human: "Ceuta / Africa (GMT +01:00)",
        offset: 60,
    },
    {
        location: "Europe/Copenhagen",
        city: "Copenhagen",
        region: "Europe",
        standard: "Copenhagen Standard Time",
        daylight: "Copenhagen Summer Time",
        human: "Copenhagen / Europe (GMT +01:00)",
        offset: 60,
    },
    {
        location: "Europe/Gibraltar",
        city: "Gibraltar",
        region: "Europe",
        standard: "Gibraltar Standard Time",
        daylight: "Gibraltar Summer Time",
        human: "Gibraltar / Europe (GMT +01:00)",
        offset: 60,
    },
    {
        location: "Africa/Lagos",
        city: "Lagos",
        region: "Africa",
        standard: "Lagos Standard Time",
        daylight: "Lagos Summer Time",
        human: "Lagos / Africa (GMT +01:00)",
        offset: 60,
    },
    {
        location: "Europe/Luxembourg",
        city: "Luxembourg",
        region: "Europe",
        standard: "Luxembourg Standard Time",
        daylight: "Luxembourg Summer Time",
        human: "Luxembourg / Europe (GMT +01:00)",
        offset: 60,
    },
    {
        location: "Europe/Madrid",
        city: "Madrid",
        region: "Europe",
        standard: "Madrid Standard Time",
        daylight: "Madrid Summer Time",
        human: "Madrid / Europe (GMT +01:00)",
        offset: 60,
    },
    {
        location: "Europe/Malta",
        city: "Malta",
        region: "Europe",
        standard: "Malta Standard Time",
        daylight: "Malta Summer Time",
        human: "Malta / Europe (GMT +01:00)",
        offset: 60,
    },
    {
        location: "Europe/Monaco",
        city: "Monaco",
        region: "Europe",
        standard: "Monaco Standard Time",
        daylight: "Monaco Summer Time",
        human: "Monaco / Europe (GMT +01:00)",
        offset: 60,
    },
    {
        location: "Africa/Ndjamena",
        city: "Ndjamena",
        region: "Africa",
        standard: "Ndjamena Standard Time",
        daylight: "Ndjamena Summer Time",
        human: "Ndjamena / Africa (GMT +01:00)",
        offset: 60,
    },
    {
        location: "Europe/Oslo",
        city: "Oslo",
        region: "Europe",
        standard: "Oslo Standard Time",
        daylight: "Oslo Summer Time",
        human: "Oslo / Europe (GMT +01:00)",
        offset: 60,
    },
    {
        location: "Europe/Paris",
        city: "Paris",
        region: "Europe",
        standard: "Paris Standard Time",
        daylight: "Paris Summer Time",
        human: "Paris / Europe (GMT +01:00)",
        offset: 60,
    },
    {
        location: "Europe/Prague",
        city: "Prague",
        region: "Europe",
        standard: "Prague Standard Time",
        daylight: "Prague Summer Time",
        human: "Prague / Europe (GMT +01:00)",
        offset: 60,
    },
    {
        location: "Europe/Rome",
        city: "Rome",
        region: "Europe",
        standard: "Rome Standard Time",
        daylight: "Rome Summer Time",
        human: "Rome / Europe (GMT +01:00)",
        offset: 60,
    },
    {
        location: "Europe/Stockholm",
        city: "Stockholm",
        region: "Europe",
        standard: "Stockholm Standard Time",
        daylight: "Stockholm Summer Time",
        human: "Stockholm / Europe (GMT +01:00)",
        offset: 60,
    },
    {
        location: "Europe/Tirane",
        city: "Tirane",
        region: "Europe",
        standard: "Tirane Standard Time",
        daylight: "Tirane Summer Time",
        human: "Tirane / Europe (GMT +01:00)",
        offset: 60,
    },
    {
        location: "Africa/Tunis",
        city: "Tunis",
        region: "Africa",
        standard: "Tunis Standard Time",
        daylight: "Tunis Summer Time",
        human: "Tunis / Africa (GMT +01:00)",
        offset: 60,
    },
    {
        location: "Europe/Vienna",
        city: "Vienna",
        region: "Europe",
        standard: "Vienna Standard Time",
        daylight: "Vienna Summer Time",
        human: "Vienna / Europe (GMT +01:00)",
        offset: 60,
    },
    {
        location: "Europe/Warsaw",
        city: "Warsaw",
        region: "Europe",
        standard: "Warsaw Standard Time",
        daylight: "Warsaw Summer Time",
        human: "Warsaw / Europe (GMT +01:00)",
        offset: 60,
    },
    {
        location: "Europe/Zurich",
        city: "Zurich",
        region: "Europe",
        standard: "Zurich Standard Time",
        daylight: "Zurich Summer Time",
        human: "Zurich / Europe (GMT +01:00)",
        offset: 60,
    },
    {
        location: "Asia/Amman",
        city: "Amman",
        region: "Asia",
        standard: "Amman Standard Time",
        daylight: "Amman Summer Time",
        human: "Amman / Asia (GMT +02:00)",
        offset: 120,
    },
    {
        location: "Europe/Athens",
        city: "Athens",
        region: "Europe",
        standard: "Athens Standard Time",
        daylight: "Athens Summer Time",
        human: "Athens / Europe (GMT +02:00)",
        offset: 120,
    },
    {
        location: "Asia/Beirut",
        city: "Beirut",
        region: "Asia",
        standard: "Beirut Standard Time",
        daylight: "Beirut Summer Time",
        human: "Beirut / Asia (GMT +02:00)",
        offset: 120,
    },
    {
        location: "Europe/Bucharest",
        city: "Bucharest",
        region: "Europe",
        standard: "Bucharest Standard Time",
        daylight: "Bucharest Summer Time",
        human: "Bucharest / Europe (GMT +02:00)",
        offset: 120,
    },
    {
        location: "Africa/Cairo",
        city: "Cairo",
        region: "Africa",
        standard: "Cairo Standard Time",
        daylight: "Cairo Summer Time",
        human: "Cairo / Africa (GMT +02:00)",
        offset: 120,
    },
    {
        location: "Europe/Chisinau",
        city: "Chisinau",
        region: "Europe",
        standard: "Chisinau Standard Time",
        daylight: "Chisinau Summer Time",
        human: "Chisinau / Europe (GMT +02:00)",
        offset: 120,
    },
    {
        location: "Asia/Damascus",
        city: "Damascus",
        region: "Asia",
        standard: "Damascus Standard Time",
        daylight: "Damascus Summer Time",
        human: "Damascus / Asia (GMT +02:00)",
        offset: 120,
    },
    {
        location: "Asia/Gaza",
        city: "Gaza",
        region: "Asia",
        standard: "Gaza Standard Time",
        daylight: "Gaza Summer Time",
        human: "Gaza / Asia (GMT +02:00)",
        offset: 120,
    },
    {
        location: "Europe/Helsinki",
        city: "Helsinki",
        region: "Europe",
        standard: "Helsinki Standard Time",
        daylight: "Helsinki Summer Time",
        human: "Helsinki / Europe (GMT +02:00)",
        offset: 120,
    },
    {
        location: "Europe/Istanbul",
        city: "Istanbul",
        region: "Europe",
        standard: "Istanbul Standard Time",
        daylight: "Istanbul Summer Time",
        human: "Istanbul / Europe (GMT +02:00)",
        offset: 120,
    },
    {
        location: "Asia/Jerusalem",
        city: "Jerusalem",
        region: "Asia",
        standard: "Jerusalem Standard Time",
        daylight: "Jerusalem Summer Time",
        human: "Jerusalem / Asia (GMT +02:00)",
        offset: 120,
    },
    {
        location: "Africa/Johannesburg",
        city: "Johannesburg",
        region: "Africa",
        standard: "Johannesburg Standard Time",
        daylight: "Johannesburg Summer Time",
        human: "Johannesburg / Africa (GMT +02:00)",
        offset: 120,
    },
    {
        location: "Europe/Kaliningrad",
        city: "Kaliningrad",
        region: "Europe",
        standard: "Kaliningrad Standard Time",
        daylight: "Kaliningrad Summer Time",
        human: "Kaliningrad / Europe (GMT +02:00)",
        offset: 120,
    },
    {
        location: "Europe/Kiev",
        city: "Kiev",
        region: "Europe",
        standard: "Kiev Standard Time",
        daylight: "Kiev Summer Time",
        human: "Kiev / Europe (GMT +02:00)",
        offset: 120,
    },
    {
        location: "Africa/Maputo",
        city: "Maputo",
        region: "Africa",
        standard: "Maputo Standard Time",
        daylight: "Maputo Summer Time",
        human: "Maputo / Africa (GMT +02:00)",
        offset: 120,
    },
    {
        location: "Asia/Nicosia",
        city: "Nicosia",
        region: "Asia",
        standard: "Nicosia Standard Time",
        daylight: "Nicosia Summer Time",
        human: "Nicosia / Asia (GMT +02:00)",
        offset: 120,
    },
    {
        location: "Europe/Riga",
        city: "Riga",
        region: "Europe",
        standard: "Riga Standard Time",
        daylight: "Riga Summer Time",
        human: "Riga / Europe (GMT +02:00)",
        offset: 120,
    },
    {
        location: "Europe/Sofia",
        city: "Sofia",
        region: "Europe",
        standard: "Sofia Standard Time",
        daylight: "Sofia Summer Time",
        human: "Sofia / Europe (GMT +02:00)",
        offset: 120,
    },
    {
        location: "Europe/Tallinn",
        city: "Tallinn",
        region: "Europe",
        standard: "Tallinn Standard Time",
        daylight: "Tallinn Summer Time",
        human: "Tallinn / Europe (GMT +02:00)",
        offset: 120,
    },
    {
        location: "Africa/Tripoli",
        city: "Tripoli",
        region: "Africa",
        standard: "Tripoli Standard Time",
        daylight: "Tripoli Summer Time",
        human: "Tripoli / Africa (GMT +02:00)",
        offset: 120,
    },
    {
        location: "Europe/Vilnius",
        city: "Vilnius",
        region: "Europe",
        standard: "Vilnius Standard Time",
        daylight: "Vilnius Summer Time",
        human: "Vilnius / Europe (GMT +02:00)",
        offset: 120,
    },
    {
        location: "Africa/Windhoek",
        city: "Windhoek",
        region: "Africa",
        standard: "Windhoek Standard Time",
        daylight: "Windhoek Summer Time",
        human: "Windhoek / Africa (GMT +02:00)",
        offset: 120,
    },
    {
        location: "Asia/Baghdad",
        city: "Baghdad",
        region: "Asia",
        standard: "Baghdad Standard Time",
        daylight: "Baghdad Summer Time",
        human: "Baghdad / Asia (GMT +03:00)",
        offset: 180,
    },
    {
        location: "Africa/Khartoum",
        city: "Khartoum",
        region: "Africa",
        standard: "Khartoum Standard Time",
        daylight: "Khartoum Summer Time",
        human: "Khartoum / Africa (GMT +03:00)",
        offset: 180,
    },
    {
        location: "Europe/Minsk",
        city: "Minsk",
        region: "Europe",
        standard: "Minsk Standard Time",
        daylight: "Minsk Summer Time",
        human: "Minsk / Europe (GMT +03:00)",
        offset: 180,
    },
    {
        location: "Europe/Moscow",
        city: "Moscow",
        region: "Europe",
        standard: "Moscow Standard Time",
        daylight: "Moscow Summer Time",
        human: "Moscow / Europe (GMT +03:00)",
        offset: 180,
    },
    {
        location: "Africa/Nairobi",
        city: "Nairobi",
        region: "Africa",
        standard: "Nairobi Standard Time",
        daylight: "Nairobi Summer Time",
        human: "Nairobi / Africa (GMT +03:00)",
        offset: 180,
    },
    {
        location: "Asia/Qatar",
        city: "Qatar",
        region: "Asia",
        standard: "Qatar Standard Time",
        daylight: "Qatar Summer Time",
        human: "Qatar / Asia (GMT +03:00)",
        offset: 180,
    },
    {
        location: "Asia/Riyadh",
        city: "Riyadh",
        region: "Asia",
        standard: "Riyadh Standard Time",
        daylight: "Riyadh Summer Time",
        human: "Riyadh / Asia (GMT +03:00)",
        offset: 180,
    },
    {
        location: "Antarctica/Syowa",
        city: "Syowa",
        region: "Antarctica",
        standard: "Syowa Standard Time",
        daylight: "Syowa Summer Time",
        human: "Syowa / Antarctica (GMT +03:00)",
        offset: 180,
    },
    {
        location: "Asia/Tehran",
        city: "Tehran",
        region: "Asia",
        standard: "Tehran Standard Time",
        daylight: "Tehran Summer Time",
        human: "Tehran / Asia (GMT +03:30)",
        offset: 210,
    },
    {
        location: "Asia/Baku",
        city: "Baku",
        region: "Asia",
        standard: "Baku Standard Time",
        daylight: "Baku Summer Time",
        human: "Baku / Asia (GMT +04:00)",
        offset: 240,
    },
    {
        location: "Asia/Dubai",
        city: "Dubai",
        region: "Asia",
        standard: "Dubai Standard Time",
        daylight: "Dubai Summer Time",
        human: "Dubai / Asia (GMT +04:00)",
        offset: 240,
    },
    {
        location: "Indian/Mahe",
        city: "Mahe",
        region: "Indian",
        standard: "Mahe Standard Time",
        daylight: "Mahe Summer Time",
        human: "Mahe / Indian (GMT +04:00)",
        offset: 240,
    },
    {
        location: "Indian/Mauritius",
        city: "Mauritius",
        region: "Indian",
        standard: "Mauritius Standard Time",
        daylight: "Mauritius Summer Time",
        human: "Mauritius / Indian (GMT +04:00)",
        offset: 240,
    },
    {
        location: "Indian/Reunion",
        city: "Reunion",
        region: "Indian",
        standard: "Reunion Standard Time",
        daylight: "Reunion Summer Time",
        human: "Reunion / Indian (GMT +04:00)",
        offset: 240,
    },
    {
        location: "Europe/Samara",
        city: "Samara",
        region: "Europe",
        standard: "Samara Standard Time",
        daylight: "Samara Summer Time",
        human: "Samara / Europe (GMT +04:00)",
        offset: 240,
    },
    {
        location: "Asia/Tbilisi",
        city: "Tbilisi",
        region: "Asia",
        standard: "Tbilisi Standard Time",
        daylight: "Tbilisi Summer Time",
        human: "Tbilisi / Asia (GMT +04:00)",
        offset: 240,
    },
    {
        location: "Asia/Yerevan",
        city: "Yerevan",
        region: "Asia",
        standard: "Yerevan Standard Time",
        daylight: "Yerevan Summer Time",
        human: "Yerevan / Asia (GMT +04:00)",
        offset: 240,
    },
    {
        location: "Asia/Kabul",
        city: "Kabul",
        region: "Asia",
        standard: "Kabul Standard Time",
        daylight: "Kabul Summer Time",
        human: "Kabul / Asia (GMT +04:30)",
        offset: 270,
    },
    {
        location: "Asia/Aqtau",
        city: "Aqtau",
        region: "Asia",
        standard: "Aqtau Standard Time",
        daylight: "Aqtau Summer Time",
        human: "Aqtau / Asia (GMT +05:00)",
        offset: 300,
    },
    {
        location: "Asia/Aqtobe",
        city: "Aqtobe",
        region: "Asia",
        standard: "Aqtobe Standard Time",
        daylight: "Aqtobe Summer Time",
        human: "Aqtobe / Asia (GMT +05:00)",
        offset: 300,
    },
    {
        location: "Asia/Ashgabat",
        city: "Ashgabat",
        region: "Asia",
        standard: "Ashgabat Standard Time",
        daylight: "Ashgabat Summer Time",
        human: "Ashgabat / Asia (GMT +05:00)",
        offset: 300,
    },
    {
        location: "Asia/Dushanbe",
        city: "Dushanbe",
        region: "Asia",
        standard: "Dushanbe Standard Time",
        daylight: "Dushanbe Summer Time",
        human: "Dushanbe / Asia (GMT +05:00)",
        offset: 300,
    },
    {
        location: "Asia/Karachi",
        city: "Karachi",
        region: "Asia",
        standard: "Karachi Standard Time",
        daylight: "Karachi Summer Time",
        human: "Karachi / Asia (GMT +05:00)",
        offset: 300,
    },
    {
        location: "Indian/Kerguelen",
        city: "Kerguelen",
        region: "Indian",
        standard: "Kerguelen Standard Time",
        daylight: "Kerguelen Summer Time",
        human: "Kerguelen / Indian (GMT +05:00)",
        offset: 300,
    },
    {
        location: "Indian/Maldives",
        city: "Maldives",
        region: "Indian",
        standard: "Maldives Standard Time",
        daylight: "Maldives Summer Time",
        human: "Maldives / Indian (GMT +05:00)",
        offset: 300,
    },
    {
        location: "Antarctica/Mawson",
        city: "Mawson",
        region: "Antarctica",
        standard: "Mawson Standard Time",
        daylight: "Mawson Summer Time",
        human: "Mawson / Antarctica (GMT +05:00)",
        offset: 300,
    },
    {
        location: "Asia/Tashkent",
        city: "Tashkent",
        region: "Asia",
        standard: "Tashkent Standard Time",
        daylight: "Tashkent Summer Time",
        human: "Tashkent / Asia (GMT +05:00)",
        offset: 300,
    },
    {
        location: "Asia/Yekaterinburg",
        city: "Yekaterinburg",
        region: "Asia",
        standard: "Yekaterinburg Standard Time",
        daylight: "Yekaterinburg Summer Time",
        human: "Yekaterinburg / Asia (GMT +05:00)",
        offset: 300,
    },
    {
        location: "Asia/Calcutta",
        city: "Calcutta",
        region: "Asia",
        standard: "Calcutta Standard Time",
        daylight: "Calcutta Summer Time",
        human: "Calcutta / Asia (GMT +05:30)",
        offset: 330,
    },
    {
        location: "Asia/Colombo",
        city: "Colombo",
        region: "Asia",
        standard: "Colombo Standard Time",
        daylight: "Colombo Summer Time",
        human: "Colombo / Asia (GMT +05:30)",
        offset: 330,
    },
    {
        location: "Asia/Katmandu",
        city: "Katmandu",
        region: "Asia",
        standard: "Katmandu Standard Time",
        daylight: "Katmandu Summer Time",
        human: "Katmandu / Asia (GMT +05:45)",
        offset: 345,
    },
    {
        location: "Asia/Almaty",
        city: "Almaty",
        region: "Asia",
        standard: "Almaty Standard Time",
        daylight: "Almaty Summer Time",
        human: "Almaty / Asia (GMT +06:00)",
        offset: 360,
    },
    {
        location: "Asia/Bishkek",
        city: "Bishkek",
        region: "Asia",
        standard: "Bishkek Standard Time",
        daylight: "Bishkek Summer Time",
        human: "Bishkek / Asia (GMT +06:00)",
        offset: 360,
    },
    {
        location: "Indian/Chagos",
        city: "Chagos",
        region: "Indian",
        standard: "Chagos Standard Time",
        daylight: "Chagos Summer Time",
        human: "Chagos / Indian (GMT +06:00)",
        offset: 360,
    },
    {
        location: "Asia/Dhaka",
        city: "Dhaka",
        region: "Asia",
        standard: "Dhaka Standard Time",
        daylight: "Dhaka Summer Time",
        human: "Dhaka / Asia (GMT +06:00)",
        offset: 360,
    },
    {
        location: "Asia/Omsk",
        city: "Omsk",
        region: "Asia",
        standard: "Omsk Standard Time",
        daylight: "Omsk Summer Time",
        human: "Omsk / Asia (GMT +06:00)",
        offset: 360,
    },
    {
        location: "Asia/Thimphu",
        city: "Thimphu",
        region: "Asia",
        standard: "Thimphu Standard Time",
        daylight: "Thimphu Summer Time",
        human: "Thimphu / Asia (GMT +06:00)",
        offset: 360,
    },
    {
        location: "Antarctica/Vostok",
        city: "Vostok",
        region: "Antarctica",
        standard: "Vostok Standard Time",
        daylight: "Vostok Summer Time",
        human: "Vostok / Antarctica (GMT +06:00)",
        offset: 360,
    },
    {
        location: "Indian/Cocos",
        city: "Cocos",
        region: "Indian",
        standard: "Cocos Standard Time",
        daylight: "Cocos Summer Time",
        human: "Cocos / Indian (GMT +06:30)",
        offset: 390,
    },
    {
        location: "Asia/Rangoon",
        city: "Rangoon",
        region: "Asia",
        standard: "Rangoon Standard Time",
        daylight: "Rangoon Summer Time",
        human: "Rangoon / Asia (GMT +06:30)",
        offset: 390,
    },
    {
        location: "Asia/Bangkok",
        city: "Bangkok",
        region: "Asia",
        standard: "Bangkok Standard Time",
        daylight: "Bangkok Summer Time",
        human: "Bangkok / Asia (GMT +07:00)",
        offset: 420,
    },
    {
        location: "Indian/Christmas",
        city: "Christmas",
        region: "Indian",
        standard: "Christmas Standard Time",
        daylight: "Christmas Summer Time",
        human: "Christmas / Indian (GMT +07:00)",
        offset: 420,
    },
    {
        location: "Antarctica/Davis",
        city: "Davis",
        region: "Antarctica",
        standard: "Davis Standard Time",
        daylight: "Davis Summer Time",
        human: "Davis / Antarctica (GMT +07:00)",
        offset: 420,
    },
    {
        location: "Asia/Hovd",
        city: "Hovd",
        region: "Asia",
        standard: "Hovd Standard Time",
        daylight: "Hovd Summer Time",
        human: "Hovd / Asia (GMT +07:00)",
        offset: 420,
    },
    {
        location: "Asia/Jakarta",
        city: "Jakarta",
        region: "Asia",
        standard: "Jakarta Standard Time",
        daylight: "Jakarta Summer Time",
        human: "Jakarta / Asia (GMT +07:00)",
        offset: 420,
    },
    {
        location: "Asia/Krasnoyarsk",
        city: "Krasnoyarsk",
        region: "Asia",
        standard: "Krasnoyarsk Standard Time",
        daylight: "Krasnoyarsk Summer Time",
        human: "Krasnoyarsk / Asia (GMT +07:00)",
        offset: 420,
    },
    {
        location: "Asia/Saigon",
        city: "Saigon",
        region: "Asia",
        standard: "Saigon Standard Time",
        daylight: "Saigon Summer Time",
        human: "Saigon / Asia (GMT +07:00)",
        offset: 420,
    },
    {
        location: "Asia/Brunei",
        city: "Brunei",
        region: "Asia",
        standard: "Brunei Standard Time",
        daylight: "Brunei Summer Time",
        human: "Brunei / Asia (GMT +08:00)",
        offset: 480,
    },
    {
        location: "Antarctica/Casey",
        city: "Casey",
        region: "Antarctica",
        standard: "Casey Standard Time",
        daylight: "Casey Summer Time",
        human: "Casey / Antarctica (GMT +08:00)",
        offset: 480,
    },
    {
        location: "Asia/Choibalsan",
        city: "Choibalsan",
        region: "Asia",
        standard: "Choibalsan Standard Time",
        daylight: "Choibalsan Summer Time",
        human: "Choibalsan / Asia (GMT +08:00)",
        offset: 480,
    },
    {
        location: "Asia/Hong Kong",
        city: "Hong Kong",
        region: "Asia",
        standard: "Hong Kong Standard Time",
        daylight: "Hong Kong Summer Time",
        human: "Hong Kong / Asia (GMT +08:00)",
        offset: 480,
    },
    {
        location: "Asia/Irkutsk",
        city: "Irkutsk",
        region: "Asia",
        standard: "Irkutsk Standard Time",
        daylight: "Irkutsk Summer Time",
        human: "Irkutsk / Asia (GMT +08:00)",
        offset: 480,
    },
    {
        location: "Asia/Kuala Lumpur",
        city: "Kuala Lumpur",
        region: "Asia",
        standard: "Kuala Lumpur Standard Time",
        daylight: "Kuala Lumpur Summer Time",
        human: "Kuala Lumpur / Asia (GMT +08:00)",
        offset: 480,
    },
    {
        location: "Asia/Macau",
        city: "Macau",
        region: "Asia",
        standard: "Macau Standard Time",
        daylight: "Macau Summer Time",
        human: "Macau / Asia (GMT +08:00)",
        offset: 480,
    },
    {
        location: "Asia/Makassar",
        city: "Makassar",
        region: "Asia",
        standard: "Makassar Standard Time",
        daylight: "Makassar Summer Time",
        human: "Makassar / Asia (GMT +08:00)",
        offset: 480,
    },
    {
        location: "Asia/Manila",
        city: "Manila",
        region: "Asia",
        standard: "Manila Standard Time",
        daylight: "Manila Summer Time",
        human: "Manila / Asia (GMT +08:00)",
        offset: 480,
    },
    {
        location: "Australia/Perth",
        city: "Perth",
        region: "Australia",
        standard: "Perth Standard Time",
        daylight: "Perth Summer Time",
        human: "Perth / Australia (GMT +08:00)",
        offset: 480,
    },
    {
        location: "Asia/Shanghai",
        city: "Shanghai",
        region: "Asia",
        standard: "Shanghai Standard Time",
        daylight: "Shanghai Summer Time",
        human: "Shanghai / Asia (GMT +08:00)",
        offset: 480,
    },
    {
        location: "Asia/Singapore",
        city: "Singapore",
        region: "Asia",
        standard: "Singapore Standard Time",
        daylight: "Singapore Summer Time",
        human: "Singapore / Asia (GMT +08:00)",
        offset: 480,
    },
    {
        location: "Asia/Taipei",
        city: "Taipei",
        region: "Asia",
        standard: "Taipei Standard Time",
        daylight: "Taipei Summer Time",
        human: "Taipei / Asia (GMT +08:00)",
        offset: 480,
    },
    {
        location: "Asia/Ulaanbaatar",
        city: "Ulaanbaatar",
        region: "Asia",
        standard: "Ulaanbaatar Standard Time",
        daylight: "Ulaanbaatar Summer Time",
        human: "Ulaanbaatar / Asia (GMT +08:00)",
        offset: 480,
    },
    {
        location: "Asia/Pyongyang",
        city: "Pyongyang",
        region: "Asia",
        standard: "Pyongyang Standard Time",
        daylight: "Pyongyang Summer Time",
        human: "Pyongyang / Asia (GMT +08:30)",
        offset: 510,
    },
    {
        location: "Asia/Dili",
        city: "Dili",
        region: "Asia",
        standard: "Dili Standard Time",
        daylight: "Dili Summer Time",
        human: "Dili / Asia (GMT +09:00)",
        offset: 540,
    },
    {
        location: "Asia/Jayapura",
        city: "Jayapura",
        region: "Asia",
        standard: "Jayapura Standard Time",
        daylight: "Jayapura Summer Time",
        human: "Jayapura / Asia (GMT +09:00)",
        offset: 540,
    },
    {
        location: "Pacific/Palau",
        city: "Palau",
        region: "Pacific",
        standard: "Palau Standard Time",
        daylight: "Palau Summer Time",
        human: "Palau / Pacific (GMT +09:00)",
        offset: 540,
    },
    {
        location: "Asia/Seoul",
        city: "Seoul",
        region: "Asia",
        standard: "Seoul Standard Time",
        daylight: "Seoul Summer Time",
        human: "Seoul / Asia (GMT +09:00)",
        offset: 540,
    },
    {
        location: "Asia/Tokyo",
        city: "Tokyo",
        region: "Asia",
        standard: "Tokyo Standard Time",
        daylight: "Tokyo Summer Time",
        human: "Tokyo / Asia (GMT +09:00)",
        offset: 540,
    },
    {
        location: "Asia/Yakutsk",
        city: "Yakutsk",
        region: "Asia",
        standard: "Yakutsk Standard Time",
        daylight: "Yakutsk Summer Time",
        human: "Yakutsk / Asia (GMT +09:00)",
        offset: 540,
    },
    {
        location: "Australia/Darwin",
        city: "Darwin",
        region: "Australia",
        standard: "Darwin Standard Time",
        daylight: "Darwin Summer Time",
        human: "Darwin / Australia (GMT +09:30)",
        offset: 570,
    },
    {
        location: "Australia/Brisbane",
        city: "Brisbane",
        region: "Australia",
        standard: "Brisbane Standard Time",
        daylight: "Brisbane Summer Time",
        human: "Brisbane / Australia (GMT +10:00)",
        offset: 600,
    },
    {
        location: "Pacific/Chuuk",
        city: "Chuuk",
        region: "Pacific",
        standard: "Chuuk Standard Time",
        daylight: "Chuuk Summer Time",
        human: "Chuuk / Pacific (GMT +10:00)",
        offset: 600,
    },
    {
        location: "Antarctica/DumontDUrville",
        city: "DumontDUrville",
        region: "Antarctica",
        standard: "DumontDUrville Standard Time",
        daylight: "DumontDUrville Summer Time",
        human: "DumontDUrville / Antarctica (GMT +10:00)",
        offset: 600,
    },
    {
        location: "Pacific/Guam",
        city: "Guam",
        region: "Pacific",
        standard: "Guam Standard Time",
        daylight: "Guam Summer Time",
        human: "Guam / Pacific (GMT +10:00)",
        offset: 600,
    },
    {
        location: "Asia/Magadan",
        city: "Magadan",
        region: "Asia",
        standard: "Magadan Standard Time",
        daylight: "Magadan Summer Time",
        human: "Magadan / Asia (GMT +10:00)",
        offset: 600,
    },
    {
        location: "Pacific/Port Moresby",
        city: "Port Moresby",
        region: "Pacific",
        standard: "Port Moresby Standard Time",
        daylight: "Port Moresby Summer Time",
        human: "Port Moresby / Pacific (GMT +10:00)",
        offset: 600,
    },
    {
        location: "Asia/Vladivostok",
        city: "Vladivostok",
        region: "Asia",
        standard: "Vladivostok Standard Time",
        daylight: "Vladivostok Summer Time",
        human: "Vladivostok / Asia (GMT +10:00)",
        offset: 600,
    },
    {
        location: "Australia/Adelaide",
        city: "Adelaide",
        region: "Australia",
        standard: "Adelaide Standard Time",
        daylight: "Adelaide Summer Time",
        human: "Adelaide / Australia (GMT +10:30)",
        offset: 630,
    },
    {
        location: "Pacific/Efate",
        city: "Efate",
        region: "Pacific",
        standard: "Efate Standard Time",
        daylight: "Efate Summer Time",
        human: "Efate / Pacific (GMT +11:00)",
        offset: 660,
    },
    {
        location: "Pacific/Guadalcanal",
        city: "Guadalcanal",
        region: "Pacific",
        standard: "Guadalcanal Standard Time",
        daylight: "Guadalcanal Summer Time",
        human: "Guadalcanal / Pacific (GMT +11:00)",
        offset: 660,
    },
    {
        location: "Australia/Hobart",
        city: "Hobart",
        region: "Australia",
        standard: "Hobart Standard Time",
        daylight: "Hobart Summer Time",
        human: "Hobart / Australia (GMT +11:00)",
        offset: 660,
    },
    {
        location: "Pacific/Kosrae",
        city: "Kosrae",
        region: "Pacific",
        standard: "Kosrae Standard Time",
        daylight: "Kosrae Summer Time",
        human: "Kosrae / Pacific (GMT +11:00)",
        offset: 660,
    },
    {
        location: "Pacific/Norfolk",
        city: "Norfolk",
        region: "Pacific",
        standard: "Norfolk Standard Time",
        daylight: "Norfolk Summer Time",
        human: "Norfolk / Pacific (GMT +11:00)",
        offset: 660,
    },
    {
        location: "Pacific/Noumea",
        city: "Noumea",
        region: "Pacific",
        standard: "Noumea Standard Time",
        daylight: "Noumea Summer Time",
        human: "Noumea / Pacific (GMT +11:00)",
        offset: 660,
    },
    {
        location: "Pacific/Pohnpei",
        city: "Pohnpei",
        region: "Pacific",
        standard: "Pohnpei Standard Time",
        daylight: "Pohnpei Summer Time",
        human: "Pohnpei / Pacific (GMT +11:00)",
        offset: 660,
    },
    {
        location: "Australia/Sydney",
        city: "Sydney",
        region: "Australia",
        standard: "Sydney Standard Time",
        daylight: "Sydney Summer Time",
        human: "Sydney / Australia (GMT +11:00)",
        offset: 660,
    },
    {
        location: "Pacific/Funafuti",
        city: "Funafuti",
        region: "Pacific",
        standard: "Funafuti Standard Time",
        daylight: "Funafuti Summer Time",
        human: "Funafuti / Pacific (GMT +12:00)",
        offset: 720,
    },
    {
        location: "Asia/Kamchatka",
        city: "Kamchatka",
        region: "Asia",
        standard: "Kamchatka Standard Time",
        daylight: "Kamchatka Summer Time",
        human: "Kamchatka / Asia (GMT +12:00)",
        offset: 720,
    },
    {
        location: "Pacific/Kwajalein",
        city: "Kwajalein",
        region: "Pacific",
        standard: "Kwajalein Standard Time",
        daylight: "Kwajalein Summer Time",
        human: "Kwajalein / Pacific (GMT +12:00)",
        offset: 720,
    },
    {
        location: "Pacific/Majuro",
        city: "Majuro",
        region: "Pacific",
        standard: "Majuro Standard Time",
        daylight: "Majuro Summer Time",
        human: "Majuro / Pacific (GMT +12:00)",
        offset: 720,
    },
    {
        location: "Pacific/Nauru",
        city: "Nauru",
        region: "Pacific",
        standard: "Nauru Standard Time",
        daylight: "Nauru Summer Time",
        human: "Nauru / Pacific (GMT +12:00)",
        offset: 720,
    },
    {
        location: "Pacific/Tarawa",
        city: "Tarawa",
        region: "Pacific",
        standard: "Tarawa Standard Time",
        daylight: "Tarawa Summer Time",
        human: "Tarawa / Pacific (GMT +12:00)",
        offset: 720,
    },
    {
        location: "Pacific/Wake",
        city: "Wake",
        region: "Pacific",
        standard: "Wake Standard Time",
        daylight: "Wake Summer Time",
        human: "Wake / Pacific (GMT +12:00)",
        offset: 720,
    },
    {
        location: "Pacific/Wallis",
        city: "Wallis",
        region: "Pacific",
        standard: "Wallis Standard Time",
        daylight: "Wallis Summer Time",
        human: "Wallis / Pacific (GMT +12:00)",
        offset: 720,
    },
    {
        location: "Pacific/Auckland",
        city: "Auckland",
        region: "Pacific",
        standard: "Auckland Standard Time",
        daylight: "Auckland Summer Time",
        human: "Auckland / Pacific (GMT +13:00)",
        offset: 780,
    },
    {
        location: "Pacific/Enderbury",
        city: "Enderbury",
        region: "Pacific",
        standard: "Enderbury Standard Time",
        daylight: "Enderbury Summer Time",
        human: "Enderbury / Pacific (GMT +13:00)",
        offset: 780,
    },
    {
        location: "Pacific/Fakaofo",
        city: "Fakaofo",
        region: "Pacific",
        standard: "Fakaofo Standard Time",
        daylight: "Fakaofo Summer Time",
        human: "Fakaofo / Pacific (GMT +13:00)",
        offset: 780,
    },
    {
        location: "Pacific/Fiji",
        city: "Fiji",
        region: "Pacific",
        standard: "Fiji Standard Time",
        daylight: "Fiji Summer Time",
        human: "Fiji / Pacific (GMT +13:00)",
        offset: 780,
    },
    {
        location: "Pacific/Tongatapu",
        city: "Tongatapu",
        region: "Pacific",
        standard: "Tongatapu Standard Time",
        daylight: "Tongatapu Summer Time",
        human: "Tongatapu / Pacific (GMT +13:00)",
        offset: 780,
    },
    {
        location: "Pacific/Apia",
        city: "Apia",
        region: "Pacific",
        standard: "Apia Standard Time",
        daylight: "Apia Summer Time",
        human: "Apia / Pacific (GMT +14:00)",
        offset: 840,
    },
    {
        location: "Pacific/Kiritimati",
        city: "Kiritimati",
        region: "Pacific",
        standard: "Kiritimati Standard Time",
        daylight: "Kiritimati Summer Time",
        human: "Kiritimati / Pacific (GMT +14:00)",
        offset: 840,
    },
];
